spring:
  # 数据源
  datasource:
    # MySQL数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ENC(ZexzBz529SG4GlfEYSrrAw==)
    # Oracle数据库
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:XE
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: hr
#    password: hr