spring:
  # 数据源
  datasource:
    # MySQL数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ENC(uHT7UzBJ6jLgXiEKaDVsjg==)