# 服务器相关
server:
  port: 9090
  servlet:
    context-path: /demo
    jsp:
      init-parameters:
        development: true
# 视图解析器
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  batch:
    initialize-schema: always
    job:
      # names: parentJob
      enabled: false
  profiles:
    # 引入分离式配置文件
    active: txt, company
  # redis相关配置
  #redis:
  #  host: 192.168.252.131
  #  port: 7001
  #  timeout: 5000
mybatis:
  type-aliases-package: com.liushihao.entity
  mapper-locations: classpath:com/liushihao/mapper/*Mapper.xml
# 日志
logging:
  # 日志等级
  level:
    root: error
    com.liushihao.dao: debug
    com.liushihao.service: info
    com.liushihao.controller: info
    com.liushihao.batch.config: info
    com.liushihao.batch.reader: info
    com.liushihao.batch.processor: info
    com.liushihao.batch.writer: info
    com.liushihao.listener: info
    #  file:
    # 输出的日志名称
    #    name: serverLog.txt
    # 输出的日志目录
  #    path: ../
    #  pattern:
    # 控制台的日志输出格式
    #    console: %d{yyyy-MM-dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
#    file: %d{yyyy-MM-dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
# 设置加密密钥 运行项目的时候 在后面拼接 --jasypt.encryptor.password=123456
jasypt:
  encryptor:
    password: chili