version: "3.1"
services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.8.8
    volumes:
      - ./data/:/var/lib/rabbitmq/
      - ./log/:/var/log/rabbitmq/log/
    ports:
      - 5672:5672
      - 15672:15672